name: archlinux package builder

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the tagged Docker image
      run: chmod -R 777 . && cd CI/arch_build/ && ./build.sh
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: arch package
        path: build/archlinux/*.tar*